name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Save secret to a file
      - name: Save Secret to File
        run: echo "${{ secrets.fetch }}" > secret.txt

      # Display the secret from the file
      - name: Display Secret
        run: cat secret.txt
