name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Fetch the secret from GitHub Secrets
      - name: Fetch Secret
        run: echo "MySecret=${{ secrets.fetch }}" >> $GITHUB_ENV

      # Display the secret in the pipeline
      - name: Display Secret
        run: echo "Secret value is $MySecret"
